package co.edu.poligran.polimarket.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AreaDeNegocioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaDeNegocioAllPropertiesEquals(AreaDeNegocio expected, AreaDeNegocio actual) {
        assertAreaDeNegocioAutoGeneratedPropertiesEquals(expected, actual);
        assertAreaDeNegocioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaDeNegocioAllUpdatablePropertiesEquals(AreaDeNegocio expected, AreaDeNegocio actual) {
        assertAreaDeNegocioUpdatableFieldsEquals(expected, actual);
        assertAreaDeNegocioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaDeNegocioAutoGeneratedPropertiesEquals(AreaDeNegocio expected, AreaDeNegocio actual) {
        assertThat(actual)
            .as("Verify AreaDeNegocio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaDeNegocioUpdatableFieldsEquals(AreaDeNegocio expected, AreaDeNegocio actual) {
        assertThat(actual)
            .as("Verify AreaDeNegocio relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaDeNegocioUpdatableRelationshipsEquals(AreaDeNegocio expected, AreaDeNegocio actual) {
        // empty method
    }
}
