package co.edu.poligran.polimarket.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EntregaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntregaAllPropertiesEquals(Entrega expected, Entrega actual) {
        assertEntregaAutoGeneratedPropertiesEquals(expected, actual);
        assertEntregaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntregaAllUpdatablePropertiesEquals(Entrega expected, Entrega actual) {
        assertEntregaUpdatableFieldsEquals(expected, actual);
        assertEntregaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntregaAutoGeneratedPropertiesEquals(Entrega expected, Entrega actual) {
        assertThat(actual)
            .as("Verify Entrega auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntregaUpdatableFieldsEquals(Entrega expected, Entrega actual) {
        assertThat(actual)
            .as("Verify Entrega relevant properties")
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEntregaUpdatableRelationshipsEquals(Entrega expected, Entrega actual) {
        assertThat(actual)
            .as("Verify Entrega relationships")
            .satisfies(a -> assertThat(a.getTarea()).as("check tarea").isEqualTo(expected.getTarea()))
            .satisfies(a -> assertThat(a.getCliente()).as("check cliente").isEqualTo(expected.getCliente()))
            .satisfies(a -> assertThat(a.getProducto()).as("check producto").isEqualTo(expected.getProducto()));
    }
}
